/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * This part needs to get included in the compilation unit where
 * blocking_handler gets defined due to the way #pragma works.
 */


/** @defgroup CM3_nvic_isrdecls_NRF52 User interrupt service routines (ISR) defaults for Nordic Semi NRF52 series
    @ingroup CM3_nvic_isrdecls

    @{*/

void power_clock_isr(void) __attribute__((weak, alias("blocking_handler")));
void radio_isr(void) __attribute__((weak, alias("blocking_handler")));
void uart0_isr(void) __attribute__((weak, alias("blocking_handler")));
void spi0_twi0_isr(void) __attribute__((weak, alias("blocking_handler")));
void spi1_twi1_isr(void) __attribute__((weak, alias("blocking_handler")));
void reserved0_isr(void) __attribute__((weak, alias("blocking_handler")));
void gpiote_isr(void) __attribute__((weak, alias("blocking_handler")));
void adc_isr(void) __attribute__((weak, alias("blocking_handler")));
void timer0_isr(void) __attribute__((weak, alias("blocking_handler")));
void timer1_isr(void) __attribute__((weak, alias("blocking_handler")));
void timer2_isr(void) __attribute__((weak, alias("blocking_handler")));
void timer3_isr(void) __attribute__((weak, alias("blocking_handler")));
void timer4_isr(void) __attribute__((weak, alias("blocking_handler")));
void rtc0_isr(void) __attribute__((weak, alias("blocking_handler")));
void temp_isr(void) __attribute__((weak, alias("blocking_handler")));
void rng_isr(void) __attribute__((weak, alias("blocking_handler")));
void ecb_isr(void) __attribute__((weak, alias("blocking_handler")));
void ccm_aar_isr(void) __attribute__((weak, alias("blocking_handler")));
void wdt_isr(void) __attribute__((weak, alias("blocking_handler")));
void rtc1_isr(void) __attribute__((weak, alias("blocking_handler")));
void qdec_isr(void) __attribute__((weak, alias("blocking_handler")));
void lpcomp_isr(void) __attribute__((weak, alias("blocking_handler")));
void swi0_isr(void) __attribute__((weak, alias("blocking_handler")));
void swi1_isr(void) __attribute__((weak, alias("blocking_handler")));
void swi2_isr(void) __attribute__((weak, alias("blocking_handler")));
void swi3_isr(void) __attribute__((weak, alias("blocking_handler")));
void swi4_isr(void) __attribute__((weak, alias("blocking_handler")));
void swi5_isr(void) __attribute__((weak, alias("blocking_handler")));

/**@}*/

/* Initialization template for the interrupt vector table. This definition is
 * used by the startup code generator (vector.c) to set the initial values for
 * the interrupt handling routines to the chip family specific _isr weak
 * symbols. */

#define IRQ_HANDLERS \
    [NVIC_POWER_CLOCK_IRQ] = power_clock_isr, \
    [NVIC_RADIO_IRQ] = radio_isr, \
    [NVIC_UART0_IRQ] = uart0_isr, \
    [NVIC_SPI0_TWI0_IRQ] = spi0_twi0_isr, \
    [NVIC_SPI1_TWI1_IRQ] = spi1_twi1_isr, \
    [NVIC_RESERVED0_IRQ] = reserved0_isr, \
    [NVIC_GPIOTE_IRQ] = gpiote_isr, \
    [NVIC_ADC_IRQ] = adc_isr, \
    [NVIC_TIMER0_IRQ] = timer0_isr, \
    [NVIC_TIMER1_IRQ] = timer1_isr, \
    [NVIC_TIMER2_IRQ] = timer2_isr, \
    [NVIC_TIMER3_IRQ] = timer3_isr, \
    [NVIC_TIMER4_IRQ] = timer4_isr, \
    [NVIC_RTC0_IRQ] = rtc0_isr, \
    [NVIC_TEMP_IRQ] = temp_isr, \
    [NVIC_RNG_IRQ] = rng_isr, \
    [NVIC_ECB_IRQ] = ecb_isr, \
    [NVIC_CCM_AAR_IRQ] = ccm_aar_isr, \
    [NVIC_WDT_IRQ] = wdt_isr, \
    [NVIC_RTC1_IRQ] = rtc1_isr, \
    [NVIC_QDEC_IRQ] = qdec_isr, \
    [NVIC_LPCOMP_IRQ] = lpcomp_isr, \
    [NVIC_SWI0_IRQ] = swi0_isr, \
    [NVIC_SWI1_IRQ] = swi1_isr, \
    [NVIC_SWI2_IRQ] = swi2_isr, \
    [NVIC_SWI3_IRQ] = swi3_isr, \
    [NVIC_SWI4_IRQ] = swi4_isr, \
    [NVIC_SWI5_IRQ] = swi5_isr
